version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3456:80"
    volumes:
      - ./frontend/src:/app/src
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://${HOST_IP:-localhost}:7433
      - NODE_ENV=development
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7433:7433"
    volumes:
      - ./backend:/app
      - ./scripts:/scripts:ro
      - ${DATA_DIR:-./data}:/data
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    environment:
      - PYTHONUNBUFFERED=1
      - SCRIPTS_DIR=/scripts
      - DATA_DIR=/data
      - LOG_LEVEL=DEBUG
      - ENABLE_GPU=1
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
